'use client';
import {useEffect,useState} from 'react';
import './governance-project-people.css';
export default function GovernanceProjectPeople(){
 const [data,setData]=useState({projects:[],people:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [search,setSearch]=useState(''),[draft,setDraft]=useState(null),[message,setMessage]=useState('');
 const [ownerEdit,setOwnerEdit]=useState(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/database/governance/project-people',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'담당 계정을 불러오지 못했습니다.');setData(d);}catch(e){setError(e.message);}finally{setLoading(false);}}
 // Synchronize the authenticated DB registry when this tab opens.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[]);
 const people=new Map(data.people.map(p=>[p.id,p]));
 const person=id=>people.get(id)||{name:'미등록 계정',email:'',department:''};
 const showPerson=(id,department=false)=>{const p=person(id);return <div key={id} className="project-person"><strong>{p.name}</strong>{department&&<span>{p.department||'부서 미등록'}</span>}<small>{p.email||'이메일 미등록'}{p.active===false?' · 비활성 계정':''}</small></div>;};
 const toggle=(key,id)=>setDraft(d=>({...d,[key]:d[key].includes(id)?d[key].filter(v=>v!==id):[...d[key],id]}));
 async function saveOwner(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/database/governance/project-people/'+encodeURIComponent(ownerEdit.no)+'/owners/'+ownerEdit.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(ownerEdit)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Owner 정보를 저장하지 못했습니다.');setOwnerEdit(null);setDraft(null);await load();window.dispatchEvent(new Event('portal-project-people-saved'));setMessage(`Owner 계정 정보를 저장했습니다. 연결 과제 ${result.affectedProjects.length}건의 현재 담당자 정보에도 반영했습니다.`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/database/governance/project-people/'+encodeURIComponent(draft.no),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({ownerIds:draft.ownerIds,developerIds:draft.developerIds,version:draft.version,reason:draft.reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||'저장하지 못했습니다.');setDraft(null);await load();window.dispatchEvent(new Event('portal-project-people-saved'));setMessage('실제 Owner·개발 담당 계정 연결을 저장했습니다.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="governance-people" aria-label="DB 담당 계정 관리">
  <header><div><h3>Project Owner · 개발 담당 계정 관리</h3><p>DB 계정 정보와 실제 과제 연결을 표시합니다. 팀장·Admin만 조회하고 변경할 수 있습니다.</p></div><button disabled={loading||busy} onClick={()=>{setError('');void load();}}>새로고침</button></header>
  <p>등록 계정을 선택하거나 Owner 정보를 직접 수정할 수 있습니다. Owner 삭제는 해당 과제 연결만 제외하며 계정과 과거 이력은 보존합니다.</p>
  <label>과제·담당자 검색<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="과제번호, 이름, 부서, 이메일"/></label>
  {loading&&<p role="status">DB 담당 계정 불러오는 중…</p>}{error&&<p role="alert" className="people-error">{error}</p>}{message&&<p role="status">{message}</p>}
  <div className="people-table"><div className="people-row people-head"><span>Agent 과제</span><span>Project Owner · 이름 / 부서 / 이메일</span><span>개발 담당자 · 이름 / 이메일</span><span>관리</span></div>
   {data.projects.filter(p=>`${p.no} ${p.name} ${[...p.ownerIds,...p.developerIds].map(id=>Object.values(person(id)).join(' ')).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(p=><div className="people-row" key={p.no}><div><strong>{p.name}</strong><small>{p.no} · {p.stage}</small></div><div>{p.ownerIds.length?p.ownerIds.map(id=><div key={id} className="owner-person-card">{showPerson(id,true)}<div className="owner-person-actions"><button aria-label={`${p.no} ${person(id).name} Owner 정보 수정`} disabled={busy||loading||!person(id).active} onClick={()=>{setError('');setMessage('');setOwnerEdit({...person(id),no:p.no,reason:''});}}>정보 수정</button><button aria-label={`${p.no} ${person(id).name} Owner 삭제`} disabled={busy||loading||p.ownerIds.length<=1} title="해당 과제에서만 제외합니다. Owner는 최소 1명이 필요합니다." onClick={()=>{setError('');setMessage('');setOwnerEdit(null);setDraft({...p,ownerIds:p.ownerIds.filter(v=>v!==id),reason:''});}}>Owner 삭제</button></div></div>):'Owner 미등록'}</div><div>{p.developerIds.length?p.developerIds.map(id=>showPerson(id)):'개발 담당자 미배정'}</div><button disabled={busy||loading} onClick={()=>{setError('');setMessage('');setOwnerEdit(null);setDraft({...p,reason:''});}}>담당 계정 변경</button></div>)}
  </div>
  {ownerEdit&&<section className="people-editor" aria-label="Owner 정보 수정"><h3>{ownerEdit.no} · Owner 정보 수정</h3><p className="owner-profile-warning">이 계정의 이름·부서·이메일을 수정하면 다른 연결 과제의 현재 담당자 정보도 함께 변경됩니다. 기존 승인 기록·문서·계정 역할은 유지됩니다. 이메일에는 본인의 실제 회사 로그인 이메일을 입력하세요.</p><div className="owner-profile-fields">{[['name','Owner 이름'],['department','Owner 부서'],['email','Owner 이메일']].map(([key,label])=><label key={key}>{label}<input type={key==='email'?'email':'text'} value={ownerEdit[key]} maxLength={key==='email'?254:200} disabled={busy} onChange={e=>setOwnerEdit({...ownerEdit,[key]:e.target.value})}/></label>)}</div><label>정보 변경 사유 (필수)<textarea value={ownerEdit.reason} maxLength={2000} disabled={busy} onChange={e=>setOwnerEdit({...ownerEdit,reason:e.target.value})}/></label><footer><button disabled={busy} onClick={()=>setOwnerEdit(null)}>취소</button><button className="primary" disabled={busy||!ownerEdit.name.trim()||!ownerEdit.email.trim()||!ownerEdit.reason.trim()} onClick={saveOwner}>{busy?'저장 중…':'Owner 정보 저장'}</button></footer></section>}
  {draft&&!ownerEdit&&<section className="people-editor" aria-label="과제 담당 계정 변경"><h3>{draft.no} · 담당 계정 변경</h3><p>선택한 계정의 DB 정보가 그대로 연결됩니다. Owner를 제외하려면 선택을 해제하고 변경 사유를 입력한 뒤 저장하세요. 계정 자체는 삭제되지 않습니다.</p>
   <div className="people-choices"><fieldset disabled={busy}><legend>Project Owner · {draft.ownerIds.length}명 선택</legend>{data.people.filter(p=>p.active||draft.ownerIds.includes(p.id)).map(p=><label key={p.id}><input type="checkbox" checked={draft.ownerIds.includes(p.id)} onChange={()=>toggle('ownerIds',p.id)} disabled={!p.active&&!draft.ownerIds.includes(p.id)}/><span><strong>{p.name}</strong><small>{p.department||'부서 미등록'} · {p.email||'이메일 미등록'}</small></span></label>)}</fieldset>
    <fieldset disabled={busy}><legend>개발 담당자 · {draft.developerIds.length}명 선택</legend>{data.people.filter(p=>(p.active&&['admin','team_leader','team_member','bts','bp_solution'].includes(p.role))||draft.developerIds.includes(p.id)).map(p=><label key={p.id}><input type="checkbox" checked={draft.developerIds.includes(p.id)} onChange={()=>toggle('developerIds',p.id)} disabled={!p.active}/><span><strong>{p.name}</strong><small>{p.email||'이메일 미등록'}</small></span></label>)}</fieldset></div>
   <label>변경 사유 (필수)<textarea value={draft.reason} maxLength={2000} disabled={busy} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
   <footer><button disabled={busy} onClick={()=>setDraft(null)}>취소</button><button className="primary" disabled={busy||!draft.ownerIds.length||!draft.reason.trim()} onClick={save}>{busy?'저장 중…':'담당 계정 저장'}</button></footer>
  </section>}
 </section>;
}
