"use client";
import {useState} from 'react';
import {INT_SECTIONS,FEA_FIELDS,standardValue,intakeRequired,feaRequired,intakeFeasibilityMetrics} from '../shared/intake-standard.mjs';
import {automaticTrackReady,classifyProject,withAutomaticFeaTrack} from '../shared/project-classification.mjs';
import {canBackfillDocument} from '../shared/historical-import-policy.mjs';
import './intake-feasibility-v3.css';
const labels={true:'예',false:'아니오',PERSONAL:'개인',TEAM:'팀',DEPT:'부서',MULTI_DEPT:'3개 부서 이상',COMPANY:'전사',LOW:'하',MEDIUM:'중',HIGH:'상',GO:'Go',CONDITIONAL:'Conditional Go',DROP:'Drop'};
function Field({field,value,onChange}) {
 return <label className="intfea-field"><span>{field.label}{field.required&&<b>필수</b>}</span>{field.type==='select'?<select value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">선택해 주세요</option>{field.options.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select>:field.type==='textarea'?<textarea value={value||''} onChange={e=>onChange(e.target.value)} maxLength={6000}/>:<input type={field.type} value={value??''} onChange={e=>onChange(e.target.value)} min={field.type==='number'?0:undefined} step={field.key.endsWith('.people')?'1':'any'}/>}</label>;
}
export function IntakeV3Fields({answers,details,onChange,readOnly=false,sectionNumber=0}) {
 const state={intakeAnswers:answers,intakeDetails:details};
 const change=(key,value)=>{const name=key.split('.')[1];if(/^\d$/.test(name)){const next=[...answers];next[Number(name)]=value;onChange(next,details);}else onChange(answers,{...details,[name]:value});};
 const sections=sectionNumber?INT_SECTIONS.filter(section=>section.number===sectionNumber):INT_SECTIONS;
 return <fieldset className="intfea-v3" disabled={readOnly}><p>INT v3.0 · 1페이지 요약. 숫자는 대략이라도 입력하고 추정 여부를 근거에 남겨 주세요.</p>{sections.map(section=><section className="intfea-section" key={section.number}><h4>{section.number}. {section.title}</h4><div className="intfea-grid">{section.fields.map(field=><Field key={field.key} field={field} value={standardValue(state,field.key)} onChange={value=>change(field.key,value)}/>)}</div></section>)}</fieldset>;
}
export function IntakeV3Summary({project}) {
 const s=key=>String(standardValue(project,key)||'미확보');
 return <div className="intfea-v3"><section className="intfea-section"><h4>1. 요구자 / 부서 / 접수일</h4><p>{project.requester} · {project.receivedDate}</p><p>Project Owner: {project.projectOwner||project.owner} · {project.projectOwnerEmail||'메일 미등록'}</p></section><section className="intfea-section"><h4>2. 어떤 업무가 힘든가요? · 필수</h4><p>{s('int.0')}</p><p>수행자: {s('int.performer')} / 월 {s('int.countPerMonth')}건 / 건당 {s('int.asIsMinutes')}분 / {s('int.people')}명</p><p>수치 근거: {s('int.quantityBasis')}</p>{project.intakeAnswers?.[1]&&<details><summary>기존 업무량 서술</summary><p>{project.intakeAnswers[1]}</p></details>}</section><section className="intfea-section"><h4>3. 지금은 어떻게 처리하나요?</h4><p>{s('int.currentProcess')}</p><p>{s('int.2')}</p></section><section className="intfea-section"><h4>4. 잘못 처리되면 어떤 일이 생기나요? · 필수</h4><p>{s('int.failureImpact')}</p></section><section className="intfea-section"><h4>5. 희망 시점과 이유</h4><p>{s('int.4')} · {s('int.timingReason')}</p></section>{project.intakeAnswers?.[3]&&<details><summary>이전 양식의 기대 결과 · 보존된 내용</summary><p>{project.intakeAnswers[3]}</p></details>}</div>;
}
export function FeaV3Fields({project,draft,onChange,readOnly=false}) {
 const normalized=withAutomaticFeaTrack({...draft,standardVersion:'3.0'});const state={...project,feaDraft:normalized};const ready=automaticTrackReady(normalized),track=classifyProject(normalized),metrics=intakeFeasibilityMetrics(state);
 const change=(key,value)=>{const [,name,index]=key.split('.');const next={...draft,standardVersion:'3.0'};if(index!==undefined){next[name]=[...(draft[name]||['','','',''])];next[name][Number(index)]=value;}else next[name]=['writeExec','sensitive','businessIdentity','damageFinancial'].includes(name)?(value===''?undefined:value==='true'):value;onChange(withAutomaticFeaTrack(next));};
 const groups=[['1. 요구 요약 · AI 자동 초안 / 수정 가능',FEA_FIELDS.slice(0,1)],['2. 대안 검토 · 필수',FEA_FIELDS.slice(1,6)],['3. 기대 효과',FEA_FIELDS.slice(6,10)],['4. 트랙·유형·자율성 판정 · 필수',FEA_FIELDS.slice(10)]];
 return <fieldset className="intfea-v3" disabled={readOnly}>{groups.map(([title,fields])=><section key={title} className="intfea-section"><h4>{title}</h4><div className="intfea-grid">{fields.map(field=><Field key={field.key} field={field} value={standardValue(state,field.key)} onChange={value=>change(field.key,value)}/>)}</div>{title.startsWith('3.')&&<p className="intfea-result">접수 기준 월 업무시간: {metrics.baselineHours===null?'수치 미확보':`${metrics.baselineHours.toFixed(1)}시간`} / 예상 절감: {metrics.savedHours===null?'근거·수치 미확보':`${metrics.savedHours.toFixed(1)}시간`}<br/>월 총 건수 × 건당 시간으로 계산합니다. 인원 수를 다시 곱하지 않습니다.</p>}{title.startsWith('4.')&&<p className="intfea-result">자동 판정 트랙: {ready?`${track.label} · ${track.signals.join(' · ')}`:'위험·범위·자율성 응답 확인 필요'}<br/>수집된 답변을 표준체계 0.3절 기준으로 계산하며 트랙은 직접 선택하지 않습니다. 자동 판정 트랙·유형·자율성은 ARD 초안으로 승계되고 담당자가 다시 확인합니다.</p>}</section>)}<section className="intfea-section"><h4>5. 작성 완료 · G1 요청</h4><p>AI 작성 내용을 담당자가 검토·보완하고 작성 완료를 누르면 G1을 요청합니다. Go·Conditional Go·Drop은 팀장님만 G1에서 판정합니다.</p>{project.g1Resolution&&<p>G1 기록: {project.g1Resolution.decision} · {project.g1Resolution.reason}</p>}</section></fieldset>;
}
export default function FeaV3Editor({project,role,readOnly=false,onSave,onComplete}) {
 const [draft,setDraft]=useState(()=>withAutomaticFeaTrack({...project.feaDraft,standardVersion:'3.0',alternatives:project.feaDraft?.alternatives||['','','',''],...(!project.feaDraft?.standardVersion?{sensitive:undefined,businessIdentity:undefined}:{}),maximumDamage:project.feaDraft?.maximumDamage||project.intakeDetails?.failureImpact||''}));
 const [message,setMessage]=useState('');const gaps=feaRequired({...project,feaDraft:draft});
 const save=(complete)=>{const normalized=withAutomaticFeaTrack(draft);if(complete&&!canBackfillDocument(project,1)){const missing=[...intakeRequired(project),...gaps];if(missing.length){setMessage(`필수 항목을 확인해 주세요: ${missing.map(f=>f.label).join(', ')}`);return;}onComplete?.(normalized);}else onSave?.(normalized);};
 return <section className="home-fea-editor"><header className="home-fea-editor-head"><div><small>{project.no}-FEA · 표준체계 v3.0</small><h3>타당성 평가서[FEA]</h3><p>AI 초안을 검토·보완한 뒤 G1을 요청합니다. Go·Conditional Go·Drop은 팀장님이 G1에서 판정합니다.</p></div><span>작성자 {project.feaAuthor?.name||'미확인'} · {readOnly?'조회 전용':'작성 중'}</span></header><FeaV3Fields project={project} draft={draft} onChange={setDraft} readOnly={readOnly}/>{!readOnly&&<footer className="home-fea-actions"><span>필수 확인 {gaps.length}개</span>{message&&<p role="alert">{message}</p>}<button className="secondary" onClick={()=>save(false)}>임시 저장</button><button className="primary" onClick={()=>save(true)}>{canBackfillDocument(project,1)?'이관 내용 저장':'FEA 작성 완료 · G1 요청'}</button></footer>}</section>;
}
