"use client";
import {useState} from 'react';
import {INT_FIELDS,FEA_FIELDS,standardValue,intakeRequired,feaRequired,intakeFeasibilityMetrics} from '../shared/intake-standard.mjs';
import {classifyProject} from '../shared/project-classification.mjs';
import {canBackfillDocument} from '../shared/historical-import-policy.mjs';
import './intake-feasibility-v3.css';
const labels={true:'예',false:'아니오',PERSONAL:'개인',TEAM:'팀',DEPT:'부서',MULTI_DEPT:'3개 부서 이상',COMPANY:'전사',GO:'Go',CONDITIONAL:'Conditional Go',DROP:'Drop'};
function Field({field,value,onChange}) {
 return <label className="intfea-field"><span>{field.label}{field.required&&<b>필수</b>}</span>{field.type==='select'?<select value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">선택해 주세요</option>{field.options.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select>:field.type==='textarea'?<textarea value={value||''} onChange={e=>onChange(e.target.value)} maxLength={6000}/>:<input type={field.type} value={value??''} onChange={e=>onChange(e.target.value)} min={field.type==='number'?0:undefined} step={field.key.endsWith('.people')?'1':'any'}/>}</label>;
}
export function IntakeV3Fields({answers,details,onChange,readOnly=false}) {
 const state={intakeAnswers:answers,intakeDetails:details};
 const change=(key,value)=>{const name=key.split('.')[1];if(/^\d$/.test(name)){const next=[...answers];next[Number(name)]=value;onChange(next,details);}else onChange(answers,{...details,[name]:value});};
 const groups=[['2. 어떤 업무가 힘든가요?',INT_FIELDS.slice(0,6)],['3. 지금은 어떻게 처리하나요?',INT_FIELDS.slice(6,8)],['4. 잘못 처리되면 어떤 일이 생기나요?',INT_FIELDS.slice(8,9)],['5. 희망 시점과 이유',INT_FIELDS.slice(9)]];
 return <fieldset className="intfea-v3" disabled={readOnly}><p>INT v3.0 · 1페이지 요약. 숫자는 대략이라도 입력하고 추정 여부를 근거에 남겨 주세요.</p>{groups.map(([title,fields])=><section className="intfea-section" key={title}><h4>{title}</h4><div className="intfea-grid">{fields.map(field=><Field key={field.key} field={field} value={standardValue(state,field.key)} onChange={value=>change(field.key,value)}/>)}</div></section>)}</fieldset>;
}
export function IntakeV3Summary({project}) {
 const s=key=>String(standardValue(project,key)||'미확보');
 return <div className="intfea-v3"><section className="intfea-section"><h4>1. 요구자 / 부서 / 접수일</h4><p>{project.requester} · {project.receivedDate}</p><p>Project Owner: {project.projectOwner||project.owner} · {project.projectOwnerEmail||'메일 미등록'}</p></section><section className="intfea-section"><h4>2. 어떤 업무가 힘든가요? · 필수</h4><p>{s('int.0')}</p><p>수행자: {s('int.performer')} / 월 {s('int.countPerMonth')}건 / 건당 {s('int.asIsMinutes')}분 / {s('int.people')}명</p><p>수치 근거: {s('int.quantityBasis')}</p>{project.intakeAnswers?.[1]&&<details><summary>기존 업무량 서술</summary><p>{project.intakeAnswers[1]}</p></details>}</section><section className="intfea-section"><h4>3. 지금은 어떻게 처리하나요?</h4><p>{s('int.currentProcess')}</p><p>{s('int.2')}</p></section><section className="intfea-section"><h4>4. 잘못 처리되면 어떤 일이 생기나요? · 필수</h4><p>{s('int.failureImpact')}</p></section><section className="intfea-section"><h4>5. 희망 시점과 이유</h4><p>{s('int.4')} · {s('int.timingReason')}</p></section>{project.intakeAnswers?.[3]&&<details><summary>이전 양식의 기대 결과 · 보존된 내용</summary><p>{project.intakeAnswers[3]}</p></details>}</div>;
}
export function FeaV3Fields({project,draft,onChange,readOnly=false}) {
 const state={...project,feaDraft:draft};const track=classifyProject({...draft,standardVersion:'3.0'}),metrics=intakeFeasibilityMetrics(state);
 const change=(key,value)=>{const [,name,index]=key.split('.');const next={...draft,standardVersion:'3.0'};if(index!==undefined){next[name]=[...(draft[name]||['','','',''])];next[name][Number(index)]=value;}else next[name]=['writeExec','sensitive','businessIdentity','damageFinancial'].includes(name)?(value===''?undefined:value==='true'):value;onChange(next);};
 const groups=[['1. 요구 요약',FEA_FIELDS.slice(0,1)],['2. 대안 검토 · 필수',FEA_FIELDS.slice(1,6)],['3. 기대 효과',FEA_FIELDS.slice(6,10)],['4. 트랙·유형 판정 · 필수',FEA_FIELDS.slice(10,18)],['5. Go / Drop 판정안 · 필수',FEA_FIELDS.slice(18)]];
 return <fieldset className="intfea-v3" disabled={readOnly}>{groups.map(([title,fields])=><section key={title} className="intfea-section"><h4>{title}</h4><div className="intfea-grid">{fields.filter(f=>f.key!=='fea.targetDate'||draft.recommendation==='GO').filter(f=>f.key!=='fea.dropAlternative'||draft.recommendation==='DROP').filter(f=>f.key!=='fea.decisionReason'||['CONDITIONAL','DROP'].includes(draft.recommendation)).map(field=><Field key={field.key} field={{...field,required:field.required||['fea.targetDate','fea.dropAlternative','fea.decisionReason'].includes(field.key)}} value={standardValue(state,field.key)} onChange={value=>change(field.key,value)}/>)}</div>{title.startsWith('3.')&&<p className="intfea-result">접수 기준 월 업무시간: {metrics.baselineHours===null?'수치 미확보':`${metrics.baselineHours.toFixed(1)}시간`} / 예상 절감: {metrics.savedHours===null?'근거·수치 미확보':`${metrics.savedHours.toFixed(1)}시간`}<br/>월 총 건수 × 건당 시간으로 계산합니다. 인원 수를 다시 곱하지 않습니다.</p>}{title.startsWith('4.')&&<p className="intfea-result">위험 기준 트랙: {FEA_FIELDS.slice(10,18).some(f=>standardValue(state,f.key)==='')?'응답 확인 필요':track.label} · {track.signals.join(' · ')}<br/>민감 개인정보는 상, 업무 식별정보는 중 이상입니다. 유형·자율성은 이 입력값을 사용합니다.</p>}</section>)}<section className="intfea-section"><h4>6. 작성 / 승인(팀장) / 일자</h4><p>작성 내용은 저장 이력에 기록됩니다. 위 판정은 작성자의 판정안이며, 공식 승인은 기존 G1 화면에서 팀장님이 확정합니다.</p>{project.g1Resolution&&<p>G1 기록: {project.g1Resolution.decision} · {project.g1Resolution.reason}</p>}</section></fieldset>;
}
export default function FeaV3Editor({project,role,readOnly=false,onSave,onComplete}) {
 const [draft,setDraft]=useState(()=>({...project.feaDraft,standardVersion:'3.0',alternatives:project.feaDraft?.alternatives||['','','',''],...(!project.feaDraft?.standardVersion?{sensitive:undefined,businessIdentity:undefined}:{}),maximumDamage:project.feaDraft?.maximumDamage||project.intakeDetails?.failureImpact||''}));
 const [message,setMessage]=useState('');const gaps=feaRequired({...project,feaDraft:draft});
 const save=(complete)=>{if(complete&&!canBackfillDocument(project,1)){const missing=[...intakeRequired(project),...gaps];if(missing.length){setMessage(`필수 항목을 확인해 주세요: ${missing.map(f=>f.label).join(', ')}`);return;}onComplete?.(draft);}else onSave?.(draft);};
 return <section className="home-fea-editor"><header className="home-fea-editor-head"><div><small>{project.no}-FEA · 표준체계 v3.0</small><h3>타당성 평가서[FEA]</h3><p>1페이지 요약 · 대안·기대 효과·위험과 판정안을 기록합니다.</p></div><span>{readOnly?'조회 전용':`${role} · 작성 중`}</span></header><FeaV3Fields project={project} draft={draft} onChange={setDraft} readOnly={readOnly}/>{!readOnly&&<footer className="home-fea-actions"><span>필수 확인 {gaps.length}개</span>{message&&<p role="alert">{message}</p>}<button className="secondary" onClick={()=>save(false)}>임시 저장</button><button className="primary" onClick={()=>save(true)}>{canBackfillDocument(project,1)?'이관 내용 저장':'FEA 작성 완료 · G1 요청'}</button></footer>}</section>;
}
