'use client';
import RpaSelect from './rpa-select';
import {useEffect,useRef,useState} from 'react';
import {X,Plus,MagnifyingGlass,CaretRight,Check,UserCircle,CalendarBlank,Clock,DownloadSimple,Paperclip,Link as LinkIcon} from '@phosphor-icons/react';
import {formatKst,kstDate} from '../shared/portal-time.mjs';
import {RPA_STATUSES,RPA_TYPES} from '../shared/rpa-policy.mjs';
import './rpa-portal.css';
import './rpa-restored.css';
import {RequestTable,MasterTable,ProjectLog,ProgressEditor} from './rpa-restored';
import MasterForm from './rpa-master-form';
import RpaRequestForm from './rpa-request-form';
import PicEditor,{ProjectDetails} from './rpa-pic-editor';
import {STATUS_LABELS,filterRpaRequests} from '../shared/rpa-display.mjs';
const statusLabels=['접수 대기','조치·개발중','현업 검증','조치 완료'];
const val=v=>v===null||v===undefined||v===''?'미등록':String(v);
function Modal({title,onClose,children}){
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus?.();};},[]);
 function keys(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 return <div className="rpa-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="rpa-modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onKeyDown={keys}><button className="rpa-close" aria-label="닫기" onClick={onClose}><X size={23}/></button>{children}</section></div>;
}
function Fields({fields}){return <dl className="rpa-fields">{Object.entries(fields).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{val(v)}</dd></div>)}</dl>;}
/** @param {{devRole?: string}} props */
export default function RpaPortal({devRole}={}){
 const [advanced,setAdvanced]=useState(false),[priority,setPriority]=useState('all'),[projectFilter,setProjectFilter]=useState('all'),[historyProject,setHistoryProject]=useState(null),[masterForm,setMasterForm]=useState(false);
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('master'),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[detail,setDetail]=useState(null),[detailTab,setDetailTab]=useState('original'),[form,setForm]=useState(null),[files,setFiles]=useState([]),[link,setLink]=useState(null),[message,setMessage]=useState('');
 async function load(){try{const r=await fetch('/api/rpa',{cache:'no-store',headers:devRole?{'x-portal-dev-role':devRole}:{}});const d=await r.json();if(!r.ok)throw Error(d.error);setError('');setData(d);}catch(e){setError(e.message);}}
 useEffect(()=>{
  const controller=new AbortController();
  fetch('/api/rpa',{cache:'no-store',signal:controller.signal,headers:devRole?{'x-portal-dev-role':devRole}:{}})
   .then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;})
   .then(d=>setData(d)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});
  return()=>controller.abort();
 },[devRole]);
 async function post(body){setBusy(true);setError('');try{const r=await fetch('/api/rpa',{method:'POST',headers:{'Content-Type':'application/json',...(devRole?{'x-portal-dev-role':devRole}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await load();return d;}catch(e){setError(e.message);return null;}finally{setBusy(false);}}
 const projects=data?.projects||[],requests=data?.requests||[],byId=new Map(projects.map(p=>[p.id,p]));
 const matches=items=>items.filter(p=>JSON.stringify(p).toLowerCase().includes(query.toLowerCase()));
 const filteredProjects=matches(projects).filter(p=>projectFilter==='all'||p.id===projectFilter),filteredRequests=filterRpaRequests(requests.map(r=>({...r,project:byId.get(r.projectId)})),{query,status,priority,projectId:projectFilter});
 const pageKey=[query,status,view,projectFilter,priority].join('|');
 const [pagination,setPagination]=useState({key:'',page:1});
 const page=pagination.key===pageKey?pagination.page:1;
 const setPage=change=>setPagination({key:pageKey,page:change(page)});
 const paged=filteredProjects.slice((page-1)*10,page*10);
 function browseProject(p){setProjectFilter(p.id);setQuery('');setStatus('all');setPriority('all');setAdvanced(true);setView('table');setHistoryProject(null);}
 function openRequest(r){setDetail({request:r,project:byId.get(r.projectId)});setDetailTab('original');}
 function newRequest(project){setError('');setFiles([]);setForm({projectId:project?.id||projects[0]?.id||'',title:'',description:'',type:RPA_TYPES[0],priority:'normal',occurredDate:kstDate(),notifyEmail:data.actor.email,log:'',key:crypto.randomUUID()});}
 async function submit(e){e.preventDefault();if(busy)return;try{const encoded=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:f.name,base64:String(reader.result).split(',')[1]});reader.onerror=reject;reader.readAsDataURL(f);})));const result=await post({...form,action:'create',files:encoded});if(result){setForm(null);setMessage('요청이 접수되었습니다.');setView('table');setStatus('all');setPriority('all');setProjectFilter('all');setQuery('');}}catch{setError('첨부파일을 읽지 못했습니다.');}}
 if(!data)return <section className="rpa-service"><h1>RPA Portal</h1><p role={error?'alert':'status'}>{error||'RPA 과제를 불러오고 있습니다.'}</p>{error&&<button onClick={load}>다시 시도</button>}</section>;
 const modalError=error&&<p role="alert" className="rpa-error">{error}</p>;
 return <section className="rpa-service">
  <div className="rpa-title"><div><p className="rpa-eyebrow">RPA OPERATIONS & MAINTENANCE</p><h1>RPA 요청 관리</h1><p className="rpa-muted">{data.canReadAll?'전체 RPA 과제와 요청 현황을 확인합니다.':'PIC 계정으로 연결된 내 RPA 과제와 요청 현황을 확인합니다.'}</p></div><button className="rpa-primary" disabled={!projects.length} onClick={()=>newRequest()}><Plus size={18}/> 오류 접수 / 개선 요청</button></div>
  {modalError}{message&&<p role="status" className="rpa-notice">{message}</p>}
  <div className="rpa-summary" aria-label="요청 처리 단계">{RPA_STATUSES.map((s,i)=><button key={s} className={'rpa-stage '+s+(status===s?' selected':'')} aria-pressed={status===s} onClick={()=>{setStatus(status===s?'all':s);setView('board');}}><span className="rpa-step-dot">{i+1}</span><span><strong>{statusLabels[i]} <em>{requests.filter(r=>r.status===s).length}건</em></strong><small>{['현업 오류 접수 · 우선순위 분류','원인 분석 · 조치 및 개발','운영 테스트 · 현업 결과 확인','조치 완료 · 처리 이력 확인'][i]}</small></span>{i<3&&<CaretRight className="rpa-stage-arrow" aria-hidden="true"/>}</button>)}</div>
  <div className="rpa-totals" aria-label="RPA 전체 집계"><span>총 관리 과제 <strong>{projects.length}개</strong></span><span>총 요청 건수 <strong>{requests.length}건</strong></span><span className="rpa-total-urgent">긴급 조치 필요 <strong>{requests.filter(r=>r.priority==='urgent'&&r.status!=='completed').length}건</strong></span></div>
  <div className="rpa-tabs" role="tablist" aria-label="RPA 화면">{[['board','진행 현황'],['table',data.canReadAll?'과제 둘러보기':'내 요청 과제 목록'],['master',data.canReadAll?'RPA 과제 마스터 시트':'내 RPA 마스터 시트'],...(data.canLink?[['links','PIC 정보 변경']]:[])].map(([id,label])=><button role="tab" aria-selected={view===id} key={id} onClick={()=>{setView(id);setStatus('all');}}>{label}{id==='master'?` (${projects.length})`:id==='links'?'':` (${requests.length})`}</button>)}</div>
  <div className="rpa-toolbar"><label className="rpa-search"><MagnifyingGlass size={20}/><input aria-label="RPA 검색" placeholder="과제 번호, 제목, PIC, 부서로 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="rpa-result-count">조회 {['board','table'].includes(view)?filteredRequests.length:filteredProjects.length} / {['board','table'].includes(view)?requests.length:projects.length}건</span><button onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced} aria-controls="rpa-detail-filters">상세필터 {advanced?'접기':'펼치기'}</button><button onClick={load}>새로고침</button></div>
  {advanced&&<div id="rpa-detail-filters" className="rpa-toolbar rpa-filter-panel"><strong>상세 조건</strong>{['board','table'].includes(view)&&<label>진행 상태<RpaSelect aria-label="진행 상태 필터" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">전체 상태</option>{Object.entries(STATUS_LABELS).map(([s,label])=><option key={s} value={s}>{label}</option>)}</RpaSelect></label>}{['board','table'].includes(view)&&<label>우선순위<RpaSelect value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">전체</option><option value="urgent">긴급</option><option value="normal">일반</option></RpaSelect></label>}<label>과제 선택<RpaSelect value={projectFilter} onChange={e=>setProjectFilter(e.target.value)}><option value="all">전체 과제</option>{projects.map(p=><option value={p.id} key={p.id}>{p.code} · {p.name}</option>)}</RpaSelect></label><button onClick={()=>{setPriority('all');setProjectFilter('all');setQuery('');setStatus('all');}}>필터 초기화</button></div>}
  {view==='master'&&data.canReadAll&&<button className="rpa-primary" onClick={()=>{setError('');setMasterForm(true);}}>신규 RPA 과제 등록</button>}
  {view==='table'&&<RequestTable requests={filteredRequests} open={openRequest}/>}
  {!projects.length&&<div className="rpa-empty">연결된 RPA 과제가 없습니다. 엑셀 PIC와 MS 계정 이메일 연결을 AI 활성화팀 팀원에게 요청해 주세요.</div>}
  {(view==='master'||view==='links')&&<>{view==='master'?<MasterTable canManage={data.canReadAll} onEdit={p=>{setError('');setMasterForm(p);}} projects={paged} requests={requests} onDetail={p=>setDetail({project:p})} onRequest={newRequest} onHistory={setHistoryProject} onBrowse={browseProject}/>:<div className="rpa-table-wrap"><table><thead><tr><th>과제 번호</th><th>과제명</th><th>법인 / 부서</th><th>PIC</th><th>{view==='links'?'PIC 정보 변경':'개발 담당자'}</th><th>상세</th></tr></thead><tbody>{paged.map(p=><tr key={p.id}><td>{p.code}</td><td><button className="rpa-row-title" onClick={()=>setDetail({project:p})}>{p.name}</button><small>{p.sourceSheet} · {p.sourceRow}행</small></td><td>{p.company}<small>{p.department}</small></td><td>{p.pics.join(', ')||'PIC 미지정'}</td><td>{view==='links'?<button className="rpa-link-pic" onClick={()=>{setError('');setLink({project:p});}}>PIC 정보 변경<small>{p.pics.length}명 · 계정 연결 {data.links.filter(l=>l.projectId===p.id).length}명</small><LinkIcon size={15}/></button>:val(p.developer)}</td><td><button aria-label={`${p.code} ${p.name} 상세`} onClick={()=>setDetail({project:p})}><CaretRight/></button></td></tr>)}</tbody></table></div>}<div className="rpa-pagination"><span>총 {filteredProjects.length}개 · {page} / {Math.max(1,Math.ceil(filteredProjects.length/10))}</span><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>이전</button><button disabled={page*10>=filteredProjects.length} onClick={()=>setPage(p=>p+1)}>다음</button></div></>}
  {view==='board'&&<div className="rpa-board">{[...RPA_STATUSES,...(requests.some(r=>r.status==='held')?['held']:[])].map(s=><section key={s} className={'rpa-kanban-column '+s}><h3>{STATUS_LABELS[s]} <small>{filteredRequests.filter(r=>r.status===s).length}</small></h3>{filteredRequests.filter(r=>r.status===s).map(r=><button className="rpa-ticket" key={r.id} onClick={()=>openRequest(r)}><div className="rpa-ticket-tags"><small>{r.code} · {r.project?.code}</small><span className={r.priority==='urgent'?'rpa-urgent':''}>{r.priority==='urgent'?'긴급':'일반'}</span></div><strong>{r.title}</strong><span>{r.type} · {r.project?.department} · {r.requester}</span><footer>{r.assignee||'담당자 미배정'}<span>상세 보기 <CaretRight size={13}/></span></footer></button>)}{!filteredRequests.some(r=>r.status===s)&&<p className="rpa-empty">등록된 요청 없음</p>}</section>)}</div>}
  {historyProject&&<Modal title="과제별 이력로그" onClose={()=>setHistoryProject(null)}><ProjectLog project={historyProject} requests={requests} onClose={()=>setHistoryProject(null)} onOpen={r=>{setHistoryProject(null);openRequest(r);}} onBrowse={browseProject}/></Modal>}
  {masterForm&&data.canReadAll&&<Modal title={typeof masterForm==='object'?'RPA 과제 정보 수정':'신규 RPA 과제 마스터 등록'} onClose={()=>{if(!busy)setMasterForm(false);}}>{modalError}<MasterForm project={typeof masterForm==='object'?masterForm:null} projects={projects} people={data.people||[]} onCancel={()=>setMasterForm(false)} busy={busy} onSave={async body=>{if(await post(body)){setMasterForm(false);setMessage(typeof masterForm==='object'?'RPA 과제 정보와 변경 이력을 저장했습니다.':'RPA 과제 마스터를 등록했습니다.');}}}/></Modal>}
  {detail&&<Modal title={detail.request?.title||detail.project.name} onClose={()=>setDetail(null)}><h2>{detail.request?.title||'RPA 과제 상세'}</h2>{detail.request?<><p className="rpa-muted">{detail.request.code} · {detail.project.code} {detail.request.priority==='urgent'&&<span className="rpa-urgent">긴급</span>}</p><div className="rpa-journey">{RPA_STATUSES.map((s,i)=>{const current=RPA_STATUSES.indexOf(detail.request.status);return <div key={s} className={i<=current?'done':''}><span>{i<current?<Check size={18}/>:i+1}</span><strong>{statusLabels[i]}</strong><small>{i===0?kstDate(detail.request.createdAt):i===3&&detail.request.completedAt?kstDate(detail.request.completedAt):'—'}</small></div>;})}</div><div className="rpa-detail-summary"><div><UserCircle/><span>담당 개발자<strong>{detail.request.assignee||'미배정'}</strong></span></div><div><CalendarBlank/><span>접수일<strong>{kstDate(detail.request.createdAt)}</strong></span></div><div><Clock/><span>반영 예정일<strong>{detail.request.expectedAt?kstDate(detail.request.expectedAt):'미정'}</strong></span></div></div><div className="rpa-tabs" role="tablist" aria-label="요청 상세">{[['original','요청 원본 정보'],['progress','진행 상황'],['history','수정 이력']].map(([id,label])=><button role="tab" aria-selected={detailTab===id} key={id} onClick={()=>setDetailTab(id)}>{label}</button>)}</div>{detailTab==='original'&&<><Fields fields={{'요청자':`${detail.request.requester} · ${detail.project.department}`,'요청 유형':detail.request.type,'발생 일시':detail.request.occurredDate,'알림 이메일':detail.request.notifyEmail,'요청 상세 내용':detail.request.description,'오류 단계':detail.request.errorStep,'에러 메시지 / 로그':detail.request.log}}/><div className="rpa-attachments"><strong>첨부파일</strong>{detail.request.files?.length?detail.request.files.map(f=><a key={f.id} href={`/api/rpa?file=${f.id}`}><Paperclip/>{f.name}<DownloadSimple/></a>):<span>첨부파일 없음</span>}</div></>}{detailTab==='progress'&&data.canReadAll&&<>{modalError}<ProgressEditor key={detail.request.id+detail.request.updatedAt} request={detail.request} developers={[...new Set(projects.map(p=>p.developer).filter(Boolean))]} busy={busy} onSave={async body=>{if(await post(body)){setDetail(null);setMessage('진행상황과 변경 이력을 저장했습니다.');}}}/></>}{detailTab==='progress'&&<Fields fields={{'현재 진행 단계':STATUS_LABELS[detail.request.status],'원인 분석':detail.request.analysis,'조치 내용':detail.request.resolution,'완료 일시':detail.request.completedAt?formatKst(detail.request.completedAt):null,'완료 메일':detail.request.mailStatus==='sent'?'발송 완료':'미발송'}}/>}{detailTab==='history'&&<ol className="rpa-history">{(detail.request.history||[]).map((h,i)=><li key={i}><strong>{h.label}</strong><span>{h.actor} · {formatKst(h.at)}</span></li>)}</ol>}<details className="rpa-source"><summary>연결된 RPA 과제 정보 · {detail.project.code}</summary><ProjectDetails project={detail.project}/></details></>:<><ProjectDetails project={detail.project}/><div className="rpa-form-actions"><button onClick={()=>setDetail(null)}>닫기</button></div></>}</Modal>}
  {form&&<Modal title="RPA 오류 수정 및 개선 요청" onClose={()=>{if(!busy)setForm(null);}}><h2>오류 접수 / 개선 요청</h2>{modalError}<RpaRequestForm form={form} setForm={setForm} projects={projects} actor={data.actor} files={files} setFiles={setFiles} setError={setError} busy={busy} onSubmit={submit} onCancel={()=>setForm(null)}/></Modal>}
  {link&&data.canLink&&<Modal title="PIC 정보 변경" onClose={()=>{if(!busy)setLink(null);}}>{modalError}<PicEditor project={link.project} links={data.links} busy={busy} onCancel={()=>setLink(null)} onSave={async body=>{if(await post(body)){setLink(null);setMessage('PIC 정보 및 계정 연결, 변경 이력을 저장했습니다.');}}}/></Modal>}
 </section>;
}
