'use client';
import {Children,useEffect,useId,useRef,useState} from 'react';
import {CaretDown,Check,MagnifyingGlass} from '@phosphor-icons/react';
import {developerKey,splitDevelopers} from '../shared/rpa-developers.mjs';
const plain=value=>Array.isArray(value)?value.map(plain).join(''):String(value??'');
/** @param {any} props */
export default function RpaSelect({value='',onChange,children,options=[],multiple=false,allowCustom=false,required=false,disabled=false,placeholder='선택해 주세요',...props}){
 const id=useId(),root=useRef(null),trigger=useRef(null),search=useRef(null);
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0),[position,setPosition]=useState({});
 const entries=options.length?options.map(o=>typeof o==='string'?{value:o,label:o}:o):Children.toArray(children).map(c=>({value:String(c.props.value??plain(c.props.children)),label:plain(c.props.children)}));
 const selected=multiple?splitDevelopers(value):[String(value)];
 const visible=entries.filter(o=>o.label.toLowerCase().includes(query.toLowerCase()));
 const label=props['aria-label']||'선택 목록';
 const close=()=>{setOpen(false);setQuery('');};
 useEffect(()=>{if(!open)return;search.current?.focus();const down=e=>{if(!(e.target instanceof Node&&root.current?.contains(e.target)))close();};const scroll=e=>{if(!root.current?.contains(e.target))close();};document.addEventListener('pointerdown',down);window.addEventListener('resize',down);document.addEventListener('scroll',scroll,true);return()=>{document.removeEventListener('pointerdown',down);window.removeEventListener('resize',down);document.removeEventListener('scroll',scroll,true);};},[open]);
 function toggle(){if(open){close();return;}const r=trigger.current.getBoundingClientRect(),below=window.innerHeight-r.bottom;setPosition({left:Math.max(8,Math.min(r.left,window.innerWidth-Math.max(r.width,240)-8)),width:Math.min(Math.max(r.width,240),window.innerWidth-16),...(below<220?{bottom:window.innerHeight-r.top+5}:{top:r.bottom+5}),maxHeight:Math.max(150,Math.min(320,below<220?r.top-16:below-16))});setActive(0);setOpen(true);}
 function pick(v){const next=multiple?(selected.some(s=>developerKey(s)===developerKey(v))?selected.filter(s=>developerKey(s)!==developerKey(v)):[...selected,v]).join(' / '):v;onChange?.({target:{value:next}});if(!multiple){close();trigger.current?.focus();}}
 function keys(e){if(!open&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();toggle();return;}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();trigger.current?.focus();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,Math.min(visible.length-1,i+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'&&open){e.preventDefault();if(visible[active])pick(visible[active].value);else if(allowCustom&&query.trim())pick(query.trim());}else if(e.key==='Tab')close();}
 const display=multiple?selected.map(v=>entries.find(o=>o.value===v)?.label||v).join(' · '):entries.find(o=>o.value===String(value))?.label||value;
 return <span className="rpa-choice" ref={root} onKeyDown={keys}><button ref={trigger} type="button" className="rpa-choice-trigger" role="combobox" aria-label={props['aria-label']} aria-expanded={open} aria-controls={id} aria-haspopup="listbox" aria-required={required} disabled={disabled} onClick={toggle}><span className={display?'':'rpa-choice-placeholder'}>{display||placeholder}</span><CaretDown size={15}/></button>{required&&<input className="rpa-choice-validation" tabIndex={-1} aria-hidden="true" required value={value} onChange={()=>{}} onInvalid={()=>trigger.current?.focus()}/>}{open&&<span className="rpa-choice-menu" style={position}><span className="rpa-choice-search"><MagnifyingGlass size={16}/><input ref={search} aria-label={`${label} 검색`} value={query} placeholder={allowCustom?'검색 또는 직접 입력':'검색'} onChange={e=>{setQuery(e.target.value);setActive(0);}}/></span><span role="listbox" id={id} aria-label={label} aria-multiselectable={multiple||undefined} className="rpa-choice-options">{visible.map((o,i)=>{const yes=selected.some(s=>multiple?developerKey(s)===developerKey(o.value):s===o.value);return <button type="button" role="option" aria-selected={yes} key={o.value} className={i===active?'is-focused':''} onMouseEnter={()=>setActive(i)} onClick={()=>pick(o.value)}><span>{o.label}</span>{yes&&<Check size={16} weight="bold"/>}</button>;})}{!visible.length&&<span className="rpa-choice-empty">검색 결과가 없습니다.</span>}</span>{allowCustom&&query.trim()&&!entries.some(o=>o.value===query.trim())&&<button type="button" className="rpa-choice-custom" onClick={()=>pick(query.trim())}>“{query.trim()}” 직접 입력</button>}{multiple&&<span className="rpa-choice-footer">{selected.length}명 선택<button type="button" onClick={()=>{close();trigger.current?.focus();}}>선택 완료</button></span>}</span>}</span>;
}
