'use client';
import {useState} from 'react';
import {Plus,Trash,UserCircle,FileText,Buildings,Gear,CalendarBlank,Desktop,Clock} from '@phosphor-icons/react';
import {formatKst} from '../shared/portal-time.mjs';
import {dayTimes} from '../shared/rpa-schedule.mjs';
import {isRpaRunDay} from '../shared/rpa-display.mjs';

export function ProjectDetails({project}){
 const f=project.fields||{};
 const show=v=>String(v??'').trim()||'미등록';
 const item=(label,value,Icon=null)=><div className="rpa-fact"><dt>{label}</dt><dd>{Icon&&<Icon size={20} aria-hidden="true"/>}{show(value)}</dd></div>;
 return <div className="rpa-detail-layout">
  <div className="rpa-detail-banner"><FileText size={32} aria-hidden="true"/><div className="rpa-detail-name"><small>과제명</small><strong>{project.name}</strong></div><dl>{item('과제번호',project.code)}{item('접수구분',f['접수타입'])}{item('진행상태',project.status)}</dl></div>
  <div className="rpa-detail-columns"><section className="rpa-detail-people"><h3><Buildings size={22}/>과제 및 담당자</h3><dl className="rpa-detail-org">{item('법인',project.company||f['법인'])}{item('본부',f['본부'])}{item('부서',project.department||f['부서'])}</dl><h4>현업 담당자 (PIC)</h4><ul className="rpa-detail-names">{(project.pics?.length?project.pics:['미지정']).map(pic=><li key={pic}><UserCircle size={22}/>{pic}</li>)}</ul><dl>{item('현업 이메일',f['현업 이메일'])}</dl><div className="rpa-detail-developer"><dl>{item('담당 개발자',project.developer||f['개발자'],UserCircle)}</dl></div></section>
  <div className="rpa-detail-operation"><section><h3><Gear size={22}/>운영 환경</h3><dl className="rpa-detail-pair">{item('운영 가상 PC',f['운영 PC'],Desktop)}{item('현업 배포일',f['현업배포일자'],CalendarBlank)}</dl><dl>{item('사용 화면 · 대상 시스템',f['사용 화면'])}</dl></section><section className="rpa-detail-schedule"><h3><CalendarBlank size={22}/>실행 일정</h3><dl className="rpa-detail-triple">{item('주기',f['주기'])}{item('실행방법',f['실행 방법'])}{item('실행일 구분',f['실행일'])}</dl><div className="rpa-detail-week" aria-label="등록된 실행 요일">{['월','화','수','목','금','토','일'].map(d=><div key={d} className={isRpaRunDay(f[d])?'active':''}><strong>{d}</strong><small>{isRpaRunDay(f[d])?(dayTimes(f)[d]||'시간 미등록'):'—'}</small></div>)}</div><dl>{item('등록된 실행 시간',f['실행 시간'],Clock)}</dl><p className="rpa-detail-note">등록된 실행 계획이며 실제 실행 결과가 아닙니다.</p><dl>{item('비고',f['비고'])}</dl></section></div></div>
  <details className="rpa-source rpa-detail-original"><summary>기타 원본 정보</summary><dl>{Object.entries(f).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}</dl><p className="rpa-muted">원본: {project.sourceSheet||'포털 등록'}{project.sourceRow?` · ${project.sourceRow}행`:''}</p></details>
 </div>;
}
export default function PicEditor({project,links,busy,onSave,onCancel}){
 const original=links.filter(l=>l.projectId===project.id);
 const [pics,setPics]=useState(()=>(project.pics||[]).map((pic,i)=>({key:i,pic,email:original.find(l=>l.pic===pic)?.email||''}))),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const changesAccess=original.some(l=>!pics.some(p=>p.pic===l.pic&&p.email.trim().toLowerCase()===l.email));
 const update=(key,field,value)=>{setPics(prev=>prev.map(p=>p.key===key?{...p,[field]:value}:p));setConfirmed(false);};
 return <form className="rpa-form" onSubmit={e=>{e.preventDefault();if(!busy&&(!changesAccess||confirmed))onSave({action:'pics',projectId:project.id,revision:project.revision??0,previousLinks:original.map(({pic,email})=>({pic,email})),pics:pics.map(({pic,email})=>({pic,email})),reason});}}><h2>PIC 정보 변경</h2><p className="rpa-muted">{project.code} · {project.name}</p><p className="rpa-pic-help">PIC를 추가하거나 이름을 수정하고 MS 계정을 연결할 수 있습니다. 이메일을 비워 두면 미연결로 저장됩니다. 연결된 사용자는 이 과제와 관련 요청을 조회할 수 있습니다.</p><div className="rpa-pic-list">{pics.map((p,i)=><div className="rpa-pic-row" key={p.key}><UserCircle size={24}/><label>PIC 이름 {i+1}<input required maxLength={100} value={p.pic} onChange={e=>update(p.key,'pic',e.target.value)}/></label><label>MS 계정 이메일<input type="email" maxLength={254} placeholder="이메일 미연결" value={p.email} onChange={e=>update(p.key,'email',e.target.value)}/></label><button type="button" aria-label={`${p.pic||i+1} PIC 삭제`} disabled={busy} onClick={()=>{setPics(prev=>prev.filter(x=>x.key!==p.key));setConfirmed(false);}}><Trash size={17}/> 삭제</button></div>)}</div>{!pics.length&&<p className="rpa-muted">등록된 PIC가 없습니다. 아래 버튼으로 추가해 주세요.</p>}<button type="button" disabled={busy||pics.length>=50} onClick={()=>setPics(prev=>[...prev,{key:crypto.randomUUID(),pic:'',email:''}])}><Plus size={16}/> PIC 추가</button><label>변경 사유<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="담당자 변경 사유를 입력해 주세요."/></label>{changesAccess&&<label className="rpa-pic-confirm"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>삭제하거나 연결 해제한 계정은 이 PIC를 통한 과제 조회 권한을 잃는 것을 확인했습니다.</label>}<div className="rpa-form-actions"><button type="button" disabled={busy} onClick={onCancel}>취소</button><button className="rpa-primary" disabled={busy}>{busy?'저장 중…':'PIC 정보 저장'}</button></div><details className="rpa-source"><summary>PIC 변경 이력</summary>{(project.history||[]).filter(h=>h.kind==='pic_updated').slice().reverse().map((h,i)=><div key={i}><strong>{formatKst(h.at)} · {h.actor}</strong><p>{h.reason}</p><p>변경 전: {h.changes.PIC.before.map(p=>`${p.pic} (${p.email||'미연결'})`).join(', ')||'없음'}</p><p>변경 후: {h.changes.PIC.after.map(p=>`${p.pic} (${p.email||'미연결'})`).join(', ')||'없음'}</p></div>)}</details></form>;
}
