"use client";
import {useState} from 'react';
import {CaretDown,Check,X} from '@phosphor-icons/react';
import {JOURNEY_V31,requiredApprovers,ROLE_LABELS,gateSummary,gateGaps,isLowRoute,historicalGateComplete,designDocumentComplete,developmentEvdComplete,releaseEvdComplete} from '../shared/workflow-v31.mjs';
import {isFastTrack,FAST_TRACK_STATUSES} from '../shared/fast-track.mjs';
import {isProjectApprover,isProjectParty,isProjectDeveloper} from '../shared/project-actors.mjs';
import {ardPartiesApproved} from '../shared/final-document.mjs';
import {pilotEvidenceLocked,pilotEvidenceReady} from '../shared/pilot-review.mjs';
import './workflow-v31.css';
export function WorkflowJourney({project,selected,onSelect}){
  const low=isLowRoute(project),fast=isFastTrack(project),fastActive=fast&&project.fastTrack?.status!==FAST_TRACK_STATUSES.REJECTED,step=Number(project.journeyStep),phase=project.deliveryPhase||'design';
  const gateRejected=gate=>gate==='G1'?project.g1Resolution?.decision==='DROP':Object.values(project.workflowApprovals?.[gate]||{}).some(v=>['REWORK','REJECTED'].includes(v?.decision));
  const currentGate=JOURNEY_V31.find(node=>node.gate&&node.step===step)?.gate;
  const returning=Boolean(currentGate&&gateRejected(currentGate));
  const visualStep=returning?step-1:step;
  const visualPhase=returning&&step===6?'development':phase;
  return <><nav className="workflow-v31-track" aria-label="6단계 개발 진행 및 승인 게이트">{JOURNEY_V31.map((n,i)=>{
    const fastExcluded=fastActive&&([1,2,4].includes(n.step)||(n.step===5&&n.phase==='design')||n.gate==='G4');
    const excluded=(low&&([3,4].includes(n.step)||(n.step===5&&n.phase==='design')))||fastExcluded,rejected=Boolean(n.gate&&gateRejected(n.gate)),active=!excluded&&!rejected&&(fastActive&&step===0?(project.intakeReview?.at?n.step===3:n.step===0):n.step===visualStep&&(!n.phase||n.phase===visualPhase)),done=!excluded&&!rejected&&(fastActive&&step===0?(n.step===0&&Boolean(project.intakeReview?.at)):n.step<visualStep||(n.phase==='design'&&visualStep===5&&visualPhase==='development'));
    const stateLabel=rejected?'보완 요청':excluded?fastActive?'GF 대체·정규화 예정':'하 트랙 적용 제외':active?'현재 단계':done?'완료':'예정';
    return <button type="button" key={i} className={[n.gate?'gate':'stage',excluded?'excluded':rejected?'rejected':active?'current':done?'done':'',selected===n.step?'selected':''].join(' ')} onClick={()=>onSelect(fastActive&&n.step===3&&step===0?0:n.step,n.phase)} aria-current={active?'step':undefined} aria-label={`${n.gate||n.number} ${n.title} · ${stateLabel}`}>{active&&<CaretDown className="workflow-current-marker" weight="fill" aria-hidden="true"/>}<span>{rejected?<X size={18} weight="bold" aria-hidden="true"/>:done?<Check size={18} weight="bold" aria-hidden="true"/>:n.gate||n.number}</span><b>{n.title}</b><small>{stateLabel}</small></button>;
  })}</nav><div className="workflow-v31-footer">{low?<span>하 트랙: G1 승인 → 개발·평가 → G3 배포 승인 → 배포·확산 → G4 확산 승인 · 요구 정의·G2·설계는 생략합니다.</span>:fastActive?<span>Fast Track: INT 인터뷰·검토 → 팀장 자격 판정 → ARD-Lite .md 작성·확정 → GF 승인 → 개발·EVD → G3 · FEA·정식 ARD·DES는 30일 내 정규화합니다.</span>:<span>필수 승인자 전원 승인 후 다음 단계로 이동합니다.</span>}</div></>;
}
function useSave(onSave){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');return {busy,message,save:async change=>{setBusy(true);setMessage('');try{const ok=await onSave(change);setMessage(ok===false?'저장하지 못했습니다. 오류 안내를 확인해 주세요.':'저장되었습니다.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}};}
export function WorkflowGate({project,gate,identity,people,onSave,onOpenRequirements}){
  const {busy,message,save}=useSave(onSave),[reason,setReason]=useState(''),[decision,setDecision]=useState('GO'),[developer,setDeveloper]=useState('');
  const role=identity?.appRole,admin=role==='admin',leader=role==='team_leader',email=(identity?.email||'').toLowerCase();
  const mine=r=>isProjectApprover(project,identity,r)&&(gate!=='G2'||r==='team_leader');
  const importing=project.historicalImport===true&&!project.historicalImportFinalizedAt;
  const expected={G1:2,G2:4,G3:6,G4:8}[gate],active=!importing&&project.journeyStep===expected,passed=project.journeyStep>expected,importedApproval=historicalGateComplete(gate,project);
  const historicalRecord=project.historicalDocuments?.[expected];
  const gaps=[...gateGaps(gate,project),...(gate==='G2'&&!ardPartiesApproved(project)?['요구 정의 화면에서 요구자·Owner 승인']:[])];
  const decided=r=>project.workflowApprovals?.[gate]?.[r]?.decision==='APPROVED'||(gate==='G1'&&r==='team_leader'&&['GO','CONDITIONAL'].includes(project.g1Resolution?.decision));
  const reworkVotes=Object.entries(project.workflowApprovals?.[gate]||{}).filter(([,vote])=>['REWORK','REJECTED'].includes(vote?.decision));
  if(gate==='G4'&&reworkVotes.length)gaps.push('개발 담당자의 파일럿 근거 보완·재저장');
  const dropped=gate==='G1'&&project.g1Resolution?.decision==='DROP';
  const supplementStage={G1:'타당성 평가',G2:'요구 정의',G3:'개발·평가',G4:'G4 확산 승인'}[gate];
  return <section className="workflow-v31-panel"><header><div><small>{gate} · 승인 게이트</small><h3>{gate==='G1'?'착수 승인':gate==='G2'?'개발 착수 승인':gate==='G3'?'배포 승인':'확산 승인'}</h3></div><strong className={importedApproval?'workflow-imported-status':undefined}>{importedApproval?'이관 승인 완료':gate==='G1'?(project.g1Resolution?.decision||'판정 대기'):gateSummary(gate,project)}</strong></header>
    {(dropped||reworkVotes.length>0)&&<div className="workflow-rework-banner"><b>{dropped?'Drop 판정':'보완 요청'} · {supplementStage} 단계로 돌아가 수정해 주세요.</b><p>{dropped?project.g1Resolution?.reason:reworkVotes.map(([role,vote])=>`${ROLE_LABELS[role]||role}: ${vote.reason||'보완 사유 확인 필요'}`).join(' · ')}</p><small>상단 진행 표시에서 {supplementStage} 단계를 선택하면 담당 개발자 또는 작성 권한자가 내용을 보완할 수 있습니다. 근거가 변경되면 기존 승인 라운드는 이력으로 보존되고 새 승인을 받습니다.</small></div>}
    {importedApproval&&<div className="workflow-imported-gate"><Check size={20} weight="bold" aria-hidden="true"/><div><b>과거 이관 승인 완료</b><p>이관 당시 선택한 현재 단계보다 앞선 {gate} 게이트의 완료 이력입니다.</p><small>기존 완료 이력을 보존하며 개별 승인자의 전자 승인을 새로 요구하지 않습니다.</small></div></div>}
    {passed&&!importedApproval&&!project.workflowApprovals?.[gate]&&<p>이전 절차의 통과 이력을 보존합니다. 신규 승인으로 대체하지 않습니다.</p>}
    {importing&&<p className="workflow-warning">과거 이관 보완 중 · 등록된 정보를 조회할 수 있습니다. 실제 승인·보완 요청은 과거 이관 완료 후 해당 단계에서 진행합니다.</p>}
    {!importing&&!active&&!passed&&<p>앞 단계를 완료한 뒤 승인할 수 있습니다.</p>}
    {project.historicalImport&&<div className="workflow-v31-vote"><div><b>요구자</b><p>{project.requester||'미등록'}</p></div><div><b>Project Owner</b><p>{project.projectOwner||project.owner||'미등록'}</p></div><div><b>개발 담당</b><p>{project.developerNames?.join(' · ')||'미배정'}</p></div><div><b>G2 확정 프로젝트 마감일</b><p>{project.committedDate||'미등록'}</p></div></div>}
    {importedApproval&&Object.entries(project.workflowApprovals?.[gate]||{}).map(([r,vote])=><div className="workflow-v31-vote" key={r}><div><b>{ROLE_LABELS[r]||r} · 등록된 승인 이력</b><p>{vote?.actorName||'승인자 미등록'} · {vote?.decision||'판정 미등록'}</p>{vote?.reason&&<p>{vote.reason}</p>}</div></div>)}
    {historicalRecord&&<details><summary>등록된 {gate} 이관 기록</summary><p>작성자: {historicalRecord.authorName||'미등록'} · 승인자: {historicalRecord.approverName||'미등록'} · 판정: {historicalRecord.decision||'미등록'}</p>{(historicalRecord.values||[]).filter(value=>typeof value==='string'&&value.trim()).map((value,i)=><p key={i}>{value}</p>)}</details>}
    {!importedApproval&&gate==='G1'&&<div className="workflow-v31-vote"><div><b>FEA 작성 담당</b><p>{project.feaAuthor?.name||project.historicalDocuments?.[1]?.authorName||'작성자 미확인'} · {project.feaCompleted?'작성 완료':'작성 중'}</p></div><div><b>G1 승인자</b><p>{project.workflowApprovals?.G1?.team_leader?.actorName||people.filter(p=>p.appRole==='team_leader').map(p=>p.displayName).join(' · ')||'팀장 판정 대기'}</p></div><div><b>개발 담당</b><p>{project.developerNames?.length?project.developerNames.join(' · '):'미배정'}</p></div></div>}
    {active&&gaps.length>0&&<p className="workflow-warning">미완료: {gaps.join(' · ')}{gate==='G4'&&<><br/>담당 개발자가 파일럿 결과 및 확산 조건을 저장하고 필수 항목을 완료한 뒤 Owner·팀장에게 승인 알림이 전달됩니다.</>}</p>}
    {gate==='G2'&&active&&<div className="workflow-warning"><b>요구 정의 최종본 작성 → 요구자·Owner 승인 → 팀장 G2 승인</b><p>요구자와 Owner의 승인 버튼은 ‘요구 정의’ 화면의 최종본 아래에 있습니다. 최종본 작성이 완료되어야 표시됩니다. 팀장은 두 역할의 승인과 마감일 확정 후 승인할 수 있습니다.</p><button type="button" onClick={onOpenRequirements}>요구 정의서 검토·승인으로 이동</button></div>}
    {!importedApproval&&requiredApprovers(gate,project).map(r=><div className="workflow-v31-vote" key={r}><div><b>{ROLE_LABELS[r]}</b><p>{project.workflowApprovals?.[gate]?.[r]?.actorName||'해당 담당자 계정으로 승인'} · {project.workflowApprovals?.[gate]?.[r]?.decision||'대기'}</p></div>{gate!=='G1'&&mine(r)&&active&&<div><button type="button" disabled={busy||decided(r)||gaps.length>0} onClick={()=>save({gateVote:{gate,role:r,decision:'APPROVED',reason}})}>{decided(r)?project.workflowApprovals?.[gate]?.[r]?.decision==='APPROVED'?'승인 완료':'판정 완료':'승인'}</button><button type="button" disabled={busy||decided(r)||!reason.trim()} onClick={()=>save({gateVote:{gate,role:r,decision:'REWORK',reason}})}>보완 요청</button></div>}</div>)}
    {active&&<label>판정 조건·보완 사유<textarea value={reason} onChange={e=>setReason(e.target.value)} /></label>}
    {gate==='G1'&&active&&<><p>팀장이 G1을 확정한 후 Admin이 개발 담당자를 배정합니다. 두 작업이 완료되면 자동 이동합니다.</p>{leader&&<div className="workflow-v31-actions"><select aria-label="G1 판정" disabled={busy||decided('team_leader')} value={decided('team_leader')?project.g1Resolution?.decision||decision:decision} onChange={e=>setDecision(e.target.value)}><option value="GO">Go</option><option value="CONDITIONAL">Conditional Go</option><option value="DROP">Drop</option></select><button type="button" disabled={busy||decided('team_leader')||gaps.length>0} onClick={()=>save({g1Resolution:{decision,reason,assignee:project.developerNames?.join(' · ')||'미배정'}})}>{decided('team_leader')?'G1 판정 완료':'팀장 G1 판정 확정'}</button></div>}{admin&&<div className="workflow-v31-actions"><select aria-label="개발 담당자" value={developer} onChange={e=>setDeveloper(e.target.value)}><option value="">개발 담당자 선택</option>{people.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><button type="button" disabled={busy||!developer||!['GO','CONDITIONAL'].includes(project.g1Resolution?.decision)} onClick={()=>save({developerIds:[developer]})}>개발 담당자 배정</button></div>}</>}
    {gate==='G3'&&active&&(admin||leader)&&<label>정보보호 승인자<select value={project.securityReviewerId||''} disabled={busy} onChange={e=>save({securityReviewerId:e.target.value})}><option value="">정보보호 담당 계정 선택</option>{people.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select><small>상 트랙 필수 · 담당자 변경 시 현재 G3 승인을 다시 받습니다.</small></label>}
    <p role="status">{busy?'저장 중…':message}</p></section>;
}
export function WorkflowControls({project,identity,people,onSave}){
  const {busy,message,save}=useSave(onSave),step=Number(project.journeyStep),gate=step<=6?'G3':'G4';
  const [evidence,setEvidence]=useState(project.gateChecks?.[gate]?.evidence||''),[criteria,setCriteria]=useState(project.gateChecks?.[gate]?.criteriaPassed||false),[zero,setZero]=useState(project.gateChecks?.G3?.zeroViolations||false);
  const [cases,setCases]=useState(''),[uat,setUat]=useState(''),[person,setPerson]=useState('');
  const admin=identity?.appRole==='admin',author=admin||isProjectDeveloper(project,identity);
  const pilotLocked=gate==='G4'&&pilotEvidenceLocked(project);
  const requester=isProjectParty(project,identity,'requester');
  if(project.historicalImport&&!project.historicalImportFinalizedAt)return null;
  if(isFastTrack(project)&&step===7)return null;
  if(![5,6,7,8].includes(step))return null;
  return <section className="workflow-v31-panel"><h3>{step<=6?'설계·개발·평가 진행 및 배포 조건':'파일럿 결과 및 확산 조건'}</h3>{step===5&&<div className="workflow-v31-actions"><span>{project.deliveryPhase==='development'?'⑤ 개발·평가 진행 중 · 최종 EVD에서 완료해 G3 요청':'④ 설계 진행 중 · 최종 DES에서 완료해 개발·평가로 이동'}</span></div>}
    {gate==='G4'&&<p>{pilotLocked?'검증 근거 저장 완료 · 읽기 전용입니다. 필수 문서가 완료되면 Owner·팀장 승인 순서로 진행합니다. 보완 요청 시 개발 담당자가 다시 작성할 수 있습니다.':'① 개발자 검증 근거 저장 → ② Owner·팀장 승인 → ③ 운영 이관'}</p>}
    {author&&<><h4>개발 담당자용 · 배포 전 검증 근거</h4><p>아래 항목은 개발 검증 결과입니다. 요구자의 업무 테스트 결과는 별도 영역에 기록합니다.</p><label><input type="checkbox" disabled={busy||pilotLocked} checked={criteria} onChange={e=>setCriteria(e.target.checked)}/>{gate==='G3'?'요구사항 성공 기준 전 항목 통과':'파일럿 종료 기준 충족'}</label>{gate==='G3'&&<label><input type="checkbox" checked={zero} onChange={e=>setZero(e.target.checked)}/>금칙 위반 0건</label>}<label>{gate==='G3'?'평가 근거 문서·버전 및 결과':'파일럿 사용 건수·오류 신고·만족도 및 종료 판정 근거'}<textarea readOnly={pilotLocked} disabled={busy} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button type="button" disabled={busy||pilotLocked||(gate==='G4'&&(!criteria||!evidence.trim()))} onClick={()=>save({gateChecks:{[gate]:{criteriaPassed:criteria,zeroViolations:zero,evidence}}})}>{pilotLocked?'검증 근거 저장 완료':'검증 근거 저장'}</button></>}
    {!author&&gate==='G4'&&<div><p>{pilotEvidenceReady(project)?'파일럿 종료 기준 충족 · 개발 담당자 확인 완료':'개발 담당자의 파일럿 검증 근거 저장을 기다리고 있습니다.'}</p>{project.gateChecks?.G4?.evidence&&<p style={{whiteSpace:'pre-wrap'}}>{project.gateChecks.G4.evidence}</p>}</div>}
    {step<=6&&<section className="workflow-uat"><h3>요구자 업무 테스트 (UAT)</h3><p>개발된 Agent가 실제 업무에서 요구사항대로 동작하는지 확인하는 단계입니다. 문서만 읽고 승인하는 절차가 아닙니다.</p><ol><li><b>테스트 준비:</b> 담당 개발자({project.developerNames?.join(' · ')||'미배정'})에게 테스트 접속 방법과 샘플 자료를 확인하세요.</li><li><b>실제 업무로 확인:</b> 요구 정의서의 성공 기준을 기준으로 정상·예외 사례를 실행하고 결과를 비교하세요.</li><li><b>결과 기록:</b> 확인한 사례 수와 기대 결과·실제 결과를 적어 주세요. 미해결 문제가 있으면 완료하지 말고 개발 담당자에게 보완을 요청하세요.</li></ol><div className="workflow-uat-reference"><strong>개발 담당자 검증 근거</strong><p>{project.gateChecks?.G3?.evidence||'아직 등록되지 않았습니다. 담당 개발자에게 테스트 방법과 검증 자료를 확인해 주세요.'}</p></div>{project.uatRecord?.completed?<div role="status"><b>업무 테스트 확인 완료</b><p>{project.uatRecord.cases}건 · {project.uatRecord.actorName}</p><p style={{whiteSpace:'pre-wrap'}}>{project.uatRecord.evidence}</p></div>:requester?<><label>테스트한 업무 사례 수 (필수)<input type="number" min="1" step="1" value={cases} placeholder="예: 전표 10건을 확인했다면 10" onChange={e=>setCases(e.target.value)}/></label><label>테스트 결과와 확인 근거 (필수)<textarea value={uat} placeholder={"예: 정상 전표 8건, 누락 항목이 있는 전표 2건을 확인했습니다.\n정상 건의 금액·거래처가 원본과 일치했고, 누락 건은 오류로 분류됐습니다.\n요구사항을 충족하며 미해결 문제는 없습니다."} onChange={e=>setUat(e.target.value)}/></label><p className="workflow-uat-note">직접 테스트해 요구사항 충족을 확인한 경우에만 완료하세요. 입력 내용과 확인자는 기록되며, 이 작업 자체가 G3 배포 승인을 대신하지는 않습니다.</p><button type="button" disabled={busy||!Number.isInteger(Number(cases))||Number(cases)<1||!uat.trim()} onClick={()=>save({uatConfirm:{cases:Number(cases),evidence:uat}})}>업무 테스트 결과 확인 완료</button></>:<p className="workflow-uat-note">실제 요구자({project.requester||'계정 연결 대기'})만 테스트 결과를 등록할 수 있습니다. Admin은 대신 완료할 수 없습니다.</p>}</section>}
    <p role="status">{busy?'저장 중…':message}</p></section>;
}
